name: Build
on:
  pull_request:
    branches: [ backend-uat ]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      # debugging sonarcloud check failure on python
      - name: check python version
        run: type -a python

      # newly added to install python
      - uses: actions/setup-python@v2

      # newly added to run the python script
      - name: Status check
        run: |
          python .github/workflows/CI-backend-integration.py

      # status check
      #- name: Status check
      #  uses: skx/github-action-tester@master
      #  with:
      #    script: .github/workflows/CI-backend-integration.py

      #- name: SonarCloud Scan
      #  uses: SonarSource/sonarcloud-github-action@master
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}