# This is a basic workflow to help you get started with Actions

name: CI-SonarCloudStatusintegration

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
env:
  SONAR_TOKEN: b33d5ab8759f652a5c6385dbe31983acfcf90019

on:
  pull_request:
    branches: [ backend-dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_SonarCloudStatusintegration:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # debugging sonarcloud check failure on python
    - name: check python version
            run: |
              which python
              type -a python
              ls -l /usr/bin/python

    - name: Status check
      uses: skx/github-action-tester@master
      with:
        script: .github/workflows/CI-backend-integration.py
